version: '3.8'

services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "65432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  dotnet-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5062"
    depends_on:
      - postgres