version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mi-sql-server
    environment:
      MSSQL_SA_PASSWORD: TuContraseñaSegura123!
      MSSQL_PID: Express
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - mi-sql-data:/var/opt/mssql
volumes:
  mi-sql-data:
