version: "3.9"
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123
      - MSSQL_PID=Developer
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
    volumes:
      - ./sql_server/data:/var/opt/mssql/data
      - ./sql_server/log:/var/opt/mssql/log
      - ./sql_server/secrets:/var/opt/mssql/secrets